openapi: 3.0.3
info:
  title: OpenAPI schema for template terraform-kubernetes-redis
components:
  schemas:
    variables:
      required: 
      - architecture
      - engine_version
      type: object
      properties:
        context:
          title: Context
          type: object
          description: |
            Receive contextual information. When Walrus deploys, Walrus will inject specific contextual information into this field.
          default: {}
          nullable: true
          additionalProperties:
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Advanced
            hidden: true
            order: 1
        infrastructure:
          title: Infrastructure
          type: object
          description: |
            Specify the infrastructure information for deploying.
          default: {}
          nullable: true
          properties:
            service_type:
              description: |
                Specify the service type of the Kubernetes cluster, default is `NodePort`.
              default: "NodePort"
              nullable: true
              title: Service Type
              type: string
              enum:
              - NodePort
              - LoadBalancer
              - ClusterIP
              x-walrus-ui:
                order: 4
            domain_suffix:
              default: cluster.local
              title: Domain Suffix
              type: string
              description: |
                Specify the domain name of the Kubernetes cluster.
              nullable: true
              x-walrus-ui:
                order: 3
            image_registry:
              default: registry-1.docker.io
              title: Image Registry
              type: string
              description: |
                Specify the image registry to pull the bitnami/redis image, default is `registry-1.docker.io`.
              nullable: true
              x-walrus-ui:
                order: 2
            namespace:
              title: Namespace
              type: string
              nullable: true
              x-walrus-ui:
                hidden: true
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Advanced
            order: 2
        architecture:
          title: Architecture
          type: string
          description: |
            Specify the deployment architecture, select from standalone or replication.
          default: standalone
          enum:
          - standalone
          - replication
          x-walrus-ui:
            group: Basic
            order: 3
        replication_readonly_replicas:
          title: Replication Readonly Replicas
          type: number
          description: |
            Specify the number of read-only replicas under the replication deployment.
          default: 1
          nullable: true
          enum:
          - 1
          - 3
          - 5
          x-walrus-ui:
            group: Basic
            order: 4
            showIf: architecture=replication
        engine_version:
          title: Engine Version
          type: string
          description: |
            Specify the deployment engine version, select from https://hub.docker.com/r/bitnami/redis/tags.
          default: "7.0"
          x-walrus-ui:
            group: Basic
            order: 5
        password:
          title: Password
          maxLength: 32
          minLength: 16
          type: string
          description: |
            Specify the account password. The password must be 16-32 characters long and start with any letter, number, or the following symbols: ! # $ % ^ & * ( ) _ + - =.
            If not specified, it will generate a random password.
          nullable: true
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 6
        resources:
          title: Resources
          type: object
          description: |
            Specify the computing resources.
          default:
            cpu: 0.25
            memory: 1024
          nullable: true
          properties:
            cpu:
              title: Cpu(Core)
              type: number
              default: 0.25
              minimum: 0.1
              nullable: true
              description: |
                Specify the cpu resources. Unit is core.
            memory:
              title: Memory(MiB)
              type: number
              default: 1024
              minimum: 512
              nullable: true
              description: |
                Specify the memory resources. Unit is megabyte.
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 7
        storage:
          title: Storage
          type: object
          description: |
            Specify the storage resources.
          nullable: true
          properties:
            class:
              title: Class
              type: string
              description: |
                Specify the storage class. If not specified, it will use the default provisioner.
              nullable: true
            size:
              default: 10240
              minimum: 1024
              title: Size(MiB)
              type: number
              description: |
                Specify the storage size. Unit is megabyte.
              nullable: true
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 8
      x-walrus-ui:
        groupOrder: 
        - Basic
        - Advanced
