openapi: 3.0.3
info:
  title: OpenAPI schema for template terraform-kubernetes-redis
components:
  schemas:
    variables:
      type: object
      properties:
        infrastructure:
          title: Infrastructure
          type: object
          description: |
            Specify the infrastructure information for deploying.
          default: {}
          properties:
            domain_suffix:
              default: cluster.local
              description: |
                Specify the domain name of the Kubernetes cluster.
              title: Domain Suffix
              type: string
              x-walrus-ui:
                order: 3
            image_registry:
              default: registry-1.docker.io
              description: |
                Specify the image registry to pull the bitnami/redis image, default is `registry-1.docker.io`.
              title: Image Registry
              type: string
              x-walrus-ui:
                order: 2
            namespace:
              title: Namespace
              type: string
              x-walrus-ui:
                hidden: true
                order: 1
            service_type:
              default: ClusterIP
              description: |
                Specify the service type of the Kubernetes cluster, default is `ClusterIP`.
              enum:
              - NodePort
              - LoadBalancer
              - ClusterIP
              title: Service Type
              type: string
              x-walrus-ui:
                order: 4
          x-walrus-ui:
            colSpan: 12
            group: Advanced
            order: 2
        architecture:
          title: Architecture
          type: string
          description: |
            Specify the deployment architecture, select from standalone or replication.
          default: standalone
          enum:
          - standalone
          - replication
          x-walrus-ui:
            group: Basic
            order: 3
        replication_readonly_replicas:
          title: Replication Readonly Replicas
          type: number
          description: |
            Specify the number of read-only replicas under the replication deployment.
          default: 1
          enum:
          - 1
          - 3
          - 5
          x-walrus-ui:
            group: Basic
            order: 4
            showIf: architecture=replication
        engine_version:
          title: Engine Version
          type: string
          description: |
            Specify the deployment engine version, select from https://hub.docker.com/r/bitnami/redis/tags.
          default: "7.0"
          x-walrus-ui:
            group: Basic
            order: 5
        password:
          title: Password
          type: string
          description: |
            Specify the account password. The password must be 16-32 characters long and start with any letter, number, or the following symbols: ! # $ % ^ & * ( ) _ + - =.
            If not specified, it will generate a random password.
          format: password
          writeOnly: true
          minLength: 16
          maxLength: 32
          x-walrus-ui:
            group: Basic
            order: 6
        resources:
          title: Resources
          type: object
          description: |
            Specify the computing resources.
          default:
            cpu: 0.25
            memory: 1024
          properties:
            cpu:
              default: 0.25
              description: |
                Specify the cpu resources. Unit is core.
              minimum: 0.1
              title: Cpu(Core)
              type: number
              x-walrus-ui:
                order: 1
            memory:
              default: 1024
              description: |
                Specify the memory resources. Unit is megabyte.
              minimum: 512
              title: Memory(MiB)
              type: number
              x-walrus-ui:
                order: 2
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 7
        storage:
          title: Storage
          type: object
          description: |
            Specify the storage resources.
          properties:
            class:
              description: |
                Specify the storage class. If not specified, it will use the default provisioner.
              title: Class
              type: string
              x-walrus-ui:
                order: 1
            size:
              default: 10240
              description: |
                Specify the storage size. Unit is megabyte.
              minimum: 1024
              title: Size(MiB)
              type: number
              x-walrus-ui:
                order: 2
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 8
      x-walrus-ui:
        groupOrder:
        - Basic
        - Advanced
